import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientOnly from "../client/ClientOnly";
import Header from "@/app/components/common/Header";
import ProgressBar from "../providers/ProgressBar";
import ChatbotMain from "@/app/components/chatbot"
import Footer from "../components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Footprynt AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <Header />
          <ChatbotMain />
        </ClientOnly>
        <ProgressBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
